### ISSUE TITLE
Aka shu yozuvlarni a href ni ichiga olib ketsayz yahshi bo'lardi 

### ISSUE THREAD

**Issue by Sayfudiinov-Samandar** [mashhurbek2005/um-my-team#2]
![Снимок экрана от 2022-07-06 19-52-32](https://user-images.githubusercontent.com/105698172/177579789-daaddde7-2c30-46e0-a7fb-38c2cac19b5a.png)

**Comment by mashhurbek2005** [comment]
bular yozuvamas logo-ku. Menimcha a ni ichiga olishdan ma'no yo'q , prosta clentlarimiz dib sanayapti
